Repository lidofinance/lido-content, pull requests merged in 2023-11, with the labels that each got.

#62 Update Ecosystem (Projects) “14fd49e1-5c25-4021-b8eb-b72228848510”
  lido-landing/ecosystem/projects/14fd49e1-5c25-4021-b8eb-b72228848510.md
Labels: netlify-cms/pending_publish

#63 Update Ecosystem (Config) “project”
  lido-landing/ecosystem/config/project.md
  lido-landing/ecosystem/projects/14fd49e1-5c25-4021-b8eb-b72228848510.md
  lido-landing/ecosystem/projects/1d855cd5-6835-4650-a357-3da9d625e9c1.md
  lido-landing/ecosystem/projects/1dfa124e-f1e1-41fc-b908-5b7f995da7c3.md
  lido-landing/ecosystem/projects/21067740-9abe-4064-8275-85ebebea51dc.md
  lido-landing/ecosystem/projects/2804ad7d-a70e-4dd7-9be3-08a4853f19f8.md
  lido-landing/ecosystem/projects/2b6f0bcd-aa43-4520-a53f-19043fe98dc8.md
  lido-landing/ecosystem/projects/3e107cf0-b41f-44b8-adcd-60ea95cb4a8d.md
  lido-landing/ecosystem/projects/4c326583-a5c4-4e62-9477-152a6e4d2291.md
  lido-landing/ecosystem/projects/51ed6e61-a170-4076-98bf-6c9f3cec9aee.md
  lido-landing/ecosystem/projects/561e5d93-440d-4174-836d-cda5334324e8.md
  lido-landing/ecosystem/projects/89bf1d4b-0a6d-4246-85df-14da2c395c87.md
  lido-landing/ecosystem/projects/8d30f884-cbdc-4270-bb9e-8f15e3ce6c00.md
  lido-landing/ecosystem/projects/b0281c6d-8278-4d80-b3b4-92527e1f8afd.md
  lido-landing/ecosystem/projects/b2cb6e94-9a83-4d05-965c-3d3a8169ea0e.md
  lido-landing/ecosystem/projects/bc573194-d2b0-48c5-a871-54f65ab63003.md
  lido-landing/ecosystem/projects/cdd2f46c-ee7f-409e-a88a-d120b3d2a320.md
  lido-landing/ecosystem/projects/d0528725-85b7-4aa7-bd0d-4c2198e90e6b.md
  lido-landing/ecosystem/projects/d8673ab3-8f88-49c0-add3-8be904383e43.md
  lido-landing/ecosystem/projects/dcd077d2-61fe-4ebf-8b65-25d2dca9f716.md
  lido-landing/ecosystem/projects/e7c5ae4d-604c-489c-9b4a-2bd244700e09.md
Labels: netlify-cms/pending_review

#65 Update Ecosystem (Projects) “2b6f0bcd-aa43-4520-a53f-19043fe98dc8”
  lido-landing/ecosystem/projects/2b6f0bcd-aa43-4520-a53f-19043fe98dc8.md
Labels: netlify-cms/pending_publish

#64 Update Ecosystem (Projects) “d8673ab3-8f88-49c0-add3-8be904383e43”
  lido-landing/ecosystem/projects/d8673ab3-8f88-49c0-add3-8be904383e43.md
Labels: netlify-cms/pending_publish

#67 Create Ecosystem (Projects) “b3c6541d-d46b-4e3d-8759-a8e59ac54dc1”
  lido-landing/ecosystem/projects/0883af83-fa74-466e-b6c8-3d4103eccaf0.md
  lido-landing/ecosystem/projects/189c2cfb-61f3-46c3-a2f4-89a0c578946d.md
  lido-landing/ecosystem/projects/32edde8d-b19a-4ff7-af8a-abbf4e5539d2.md
  lido-landing/ecosystem/projects/3a3459c1-eb22-49b9-ae83-67678f22e7bd.md
  lido-landing/ecosystem/projects/6fb1c3ab-21d0-419f-91ab-284c2e68ad40.md
  lido-landing/ecosystem/projects/7e8f0d89-6dcc-470f-aac0-53acbf94a28a.md
  lido-landing/ecosystem/projects/b4499124-fb01-4bbd-b563-b81c96f2e9ad.md
  lido-landing/ecosystem/projects/c9be713c-3417-425f-9272-d3c53f31ee50.md
  lido-landing/ecosystem/projects/e59f0de4-22fa-4cc4-8a37-8f9e756a3bae.md
Labels: netlify-cms/draft
