Repository lidofinance/lido-content, pull requests merged in 2025-02, with the labels that each got.

#249 Update Projects “9a8db764-c027-4709-8202-4a68eaad988c”
  banners/9a8db764-c027-4709-8202-4a68eaad988c.md
Labels: netlify-cms/draft

#261 Create Multichain (Projects) “f9aefd8d-e707-4769-bf31-9f8d64bbccb1”
  lido-landing/multichain/projects/f9aefd8d-e707-4769-bf31-9f8d64bbccb1.md
Labels: netlify-cms/draft

#262 Update Lido landing “multichain”
  lido-landing/multichain/multichain.md
Labels: netlify-cms/draft

#263 Update Projects “9a8db764-c027-4709-8202-4a68eaad988c”
  banners/9a8db764-c027-4709-8202-4a68eaad988c.md
Labels: netlify-cms/draft

#264 Update Lido landing “faq”
  lido-landing/faq.md
Labels: netlify-cms/draft

#265 Update Projects “9a8db764-c027-4709-8202-4a68eaad988c”
  banners/9a8db764-c027-4709-8202-4a68eaad988c.md
Labels: netlify-cms/draft

#266 Update Lido landing “scorecard”
  lido-landing/scorecard.md
Labels: netlify-cms/draft

#269 Update Projects “9a8db764-c027-4709-8202-4a68eaad988c”
  banners/9a8db764-c027-4709-8202-4a68eaad988c.md
Labels: netlify-cms/draft

#272 Update Lido landing “scorecard”
  lido-landing/scorecard.md
Labels: netlify-cms/draft

#273 Update Emergency Banner “emergencyBanner”
  lido-landing/emergencyBanner.md
Labels: netlify-cms/pending_publish

#274 Update Multichain (Projects) “f9aefd8d-e707-4769-bf31-9f8d64bbccb1”
  lido-landing/multichain/projects/f9aefd8d-e707-4769-bf31-9f8d64bbccb1.md
Labels: netlify-cms/draft

#275 Update Lido landing “multichain”
  lido-landing/multichain/multichain.md
Labels: netlify-cms/draft

#277 Update Emergency Banner “emergencyBanner”
  lido-landing/emergencyBanner.md
Labels: netlify-cms/pending_review

#278 Update Lido landing “node-operators”
  lido-landing/node-operators.md
Labels: netlify-cms/draft

#279 Update stETH in DEFI (Projects) “796e7e87-a7ab-46f0-806d-3f6211d7a2ae”
  lido-landing/steth-in-defi/projects/796e7e87-a7ab-46f0-806d-3f6211d7a2ae.md
Labels: netlify-cms/draft
